baseURL: 'https://snippets.snhd.co/'
languageCode: en-gb
title: Snippets
theme: papermod
params:
  ShowReadingTime: true
  homeInfoParams:
    Title: "Hello"
    Content: Quick and rough notes
  socialIcons:
    - name: twitter
      url: 'https://twitter.com/SeanHood'
    - name: github
      url: 'https://github.com/SeanHood'

